# python-app/catalog-info.yaml  (reemplazar todo el contenido)
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: python-app-catalog
  description: Location raíz — Component, Group y User de python-app
spec:
  type: url
  targets:
    - ./catalog/component.yaml
    - ./catalog/groups.yaml
    - ./catalog/users.yaml