site_name: 'python-app'
site_description: 'Main documentation for python-app'
repo_url: https://github.com/juancrespo25/python-app
docs_dir: docs # Markdown. Nunca ".". Sin cambio.

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: index.md
      - Arquitectura: arquitectura.md 