apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.service.port | int }}
    targetPort: {{ .Values.deployment.port | int }}
    protocol: TCP
